### PR TITLE
faster optical flow

### PR DESCRIPTION
**Pull request by schwittlick**

### CODE REVIEW

**Comment by mrzl** [comment]
I removed deepmatching completely.. No idea what this was for tbh.

**Comment by zeruniverse** [comment]
I’ll test on my computer ASAP

**Comment by zeruniverse** [comment]
@mrzl I encountered an error on my computer:

```
[jeffery@JefferyPC tmp]$ chmod 777 run_OF_RGB 
[jeffery@JefferyPC tmp]$ ./run_OF_RGB 
./run_OF_RGB: error while loading shared libraries: libopencv_highgui.so.2.4: cannot open shared object file: No such file or directory
```
I would suggest to write a documentation about how to compile run_OF_RGB

**Comment by mrzl** [comment]
Yeah, I agree. Can you try one short test before, please. Just install opencv

    sudo apt install libopencv*


Possibly that might already work out.. Possibly there's another one missing after that, let's try. If this gets too complicated, I'd write up a short documentation and we're set.

**Comment by zeruniverse** [comment]
Sorry I was on vacation these days. I think it’s good to write a doc about the compiling anyway since Ubuntu is not the only target system (and linked library path might be different in other systems)

**Comment by zeruniverse** [comment]
I missed your point. Sorry. deepmatching is needed for deepflow

**Comment by Lyken17** [comment]
After a recent group meeting, I realize the deep match + deepflow is not necessary -- which can be replaced with other end-to-end optical flow estimators, e.g. [FlowNet](https://arxiv.org/abs/1612.01925). If I have time this semester, I will rewrite the code and release a PyTorch version.

**Comment by matanox** [comment]
I wonder if I can get this stage running currently on a box with a newer version of OpenCV. 

```
./run_OF_RGB: error while loading shared libraries: libopencv_highgui.so.2.4: cannot open shared object file: No such file or directory
Exception EFilterIncompatibleSize: Initial container size: 0  Resulting container size: 0
```

**Pull request merged**
